services:
  kriss-db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
        - kriss-data:/var/lib/postgresql
    env_file: .env

volumes:
  kriss-data:
